### ISSUE TITLE
When do you expect to upgrade this package to support dbt 1.0.0? 

### ISSUE THREAD

**Issue by jcbmllgn** [entechlog/dbt-snow-mask#16]
Thanks for creating this package! I'm curious if/when you expect to upgrade this to be compatible with dbt 1.0.0?

**Comment by rumbin** [comment]
That would indeed be great!

Are you expecting any incompatibilities or will it suffice to adjust the `require-dbt-version`?

**Comment by entechlog** [comment]
@jcbmllgn , Sorry for the delay in getting back on this one. This has been taken care now in lastest version of the package and should in dbt hub soon

https://github.com/entechlog/dbt-snow-mask/pull/15
