### ISSUE TITLE
Missing packages.yml file

### ISSUE THREAD

**Issue by graciegoheen** [entechlog/dbt-snow-mask#19]
This project uses a `dbt_utils` function (`get_query_results_as_dict` in the `apply_masking_policy_list_for_sources.sql` macro) but doesn't have `dbt_utils` installed. If someone is using this package, but has not yet independently installed `dbt_utils`, they will get the error:
`'dbt_utils' is undefined`

Add a `packages.yml` file with dbt_utils installed.

**Comment by entechlog** [comment]
@graciegoheen dbt_utils was not added to this package just to avoid version conflicts with someone who uses dbt_utils in the project but with a different version than the one mentioned in the package.

That being said, do you still see this approach is an issue ?

**Comment by graciegoheen** [comment]
I see - maybe just a note, then, in the installation steps that this project uses `dbt_utils`, and the user will get an error if they attempt to use this package without _also_ installing `dbt_utils`?

**Comment by entechlog** [comment]
@graciegoheen , Thank you for the suggestion. I have updated the instructions on https://github.com/entechlog/dbt-snow-mask#installation-instructions to add this note.
