### ISSUE TITLE
Fix masking policy schema only, not db

### ISSUE THREAD

**Issue by mbritton-neuroflow** [entechlog/dbt-snow-mask#31]
Hello, thanks for this great package!

I would like to use the `use_common_masking_policy_db` functionality to fix only the schema, but not the database. So for example my masking policies will always live in the `public` schema, but I want to maintain separation between my prod and dev environments. Otherwise as I understand it testing out a new masking policy definition in dev could update my prod environment!

If my understanding is correct, and this change fits in with your product vision, I'd be happy to contribute a fork. The line in question is [here](https://github.com/entechlog/dbt-snow-mask/blob/0.1.9/macros/snow-mask/create-policy/create_masking_policy.sql#L19), should be a pretty simple change.

**Comment by mbritton-neuroflow** [comment]
Hi! Yes, that looks like it accomplishes what I was looking for. I am OOO until June 13th but I will test when I return. Thank you!

**Comment by entechlog** [comment]
@mbritton-neuroflow , Thank You and will wait for your test feedback before I close this issue
