### ISSUE TITLE
unapply_masking_policy fails for incremental models

### ISSUE THREAD

**Issue by rumbin** [entechlog/dbt-snow-mask#4]
The 
```
{% if materialization == "incremental" %}
    {% set materialization = "table" %}
{% endif %}
```
logic is missing for the `unapply` action.

**Comment by entechlog** [comment]
@rumbin , Just fixed this in https://github.com/entechlog/dbt-snow-mask/pull/8

Could you please review and let me know, will do a release in a day OR two after I review other open issues as well.

**Comment by rumbin** [comment]
@entechlog Looks good; thanks for taking care!
