### ISSUE TITLE
Ability to update existing masking functions

### ISSUE THREAD

**Issue by brianschillaci** [entechlog/dbt-snow-mask#48]
Hello!

My team has started using this package for masking and it's been working awesome. But one thing we ran into is having to manually update the masking functions (alter function statements) if for example we needed to add an additional role to the masking targets.

Is the only way to do this currently through dbt to unapply all masking, drop the functions, recreate functions and reapply them?
Ideally we wouldn't want to do this because it would expose sensitive data for a short period of time. I might be missing some functionality that already exists?

Thanks!

**Comment by entechlog** [comment]
Thank You for the feedback and the future request. Can you check the recent release candidate and see if this helps to fix the issue ?

- https://github.com/entechlog/dbt-snow-mask/issues/46
- https://github.com/entechlog/dbt-snow-mask/releases/tag/0.2.3rc1

**Comment by brianschillaci** [comment]
Yep, that's what we were looking for as well. Thank you!
